### ISSUE TITLE
Streamline the features section.

### ISSUE THREAD

**Issue by C0rvust** [deathcrafter/ASimpleVisualizer#6]
1. Choose from two audio plugins, AudioLevel plugin by d-grace (rainmeter default) and AudioAnalyzer plugin by rxtd (external).

2. Customization options, i.e.:
- mirroring along x/y axis, reflection, etc.
- designate an image as the visualizer's background.
- built in gradient generator to create gradients for the visualizer.

3. Settings menu for the aforementioned customization.

**Comment by sceleri** [comment]
Fixed.
